apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-app
  namespace: lab-zone
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      imagePullSecrets:
      - name: harbor-pull-secret
      containers:
      - name: nginx
        # Replace with your actual Harbor domain address
        image: harbor100.waltonbd.com:8443/lab-apps/hello-nginx:v1
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: lab-zone
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: nginx
